name: Dispatch CI

on:
  # At 11:55 PM UTC, only on Thursday and Friday
  schedule:
    - cron: '55 23 * * 4,5'

jobs:
  dispatch-ci:
    name: Dispatch CI
    # Only run cron on the tractorcow-farm account
    if: (github.event_name == 'schedule' && github.repository_owner == 'tractorcow-farm') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch CI
        uses: silverstripe/gha-dispatch-ci@v1
